Add config option to opt-out of generating CSRF token
QueraTeam/django-nextjs pull request #32
Opened 2024-07-01 20:51 UTC by Lizards

- This adds a config option `ensure_csrf_token` to opt-out of `django-nextjs` automatically generating a CSRF token to include in the request to the NextJS server.  It preserves the current behavior by defaulting to `True`.
  - The comment in `_get_nextjs_request_cookies` indicates this was done to support a GraphQL use case.  But in our project, the behavior is undesirable because of the side-effect of including a `Set-Cookie` header (see next bullet).

- A new CSRF token value was being generated on every request.  This causes Django's `CsrfViewMiddleware` to include a `Set-Cookie` header on every response, making all responses from `django-nextjs` un-cacheable.  This updates the behavior to only generate a CSRF token if the `settings.CSRF_COOKIE_NAME` cookie is not already present in the request.

2024-07-07 06:55 UTC, danialkeimasi requested changes

2024-07-07 06:55 UTC, danialkeimasi commented on django_nextjs/render.py
> +    if all([ENSURE_CSRF_TOKEN, settings.CSRF_COOKIE_NAME not in unreserved_cookies]):
This is technically correct, but I prefer using a simple `and` between the two conditions for better readability.

2024-07-07 06:55 UTC, danialkeimasi commented on README.md
> +installed, he initial response will include a `Set-Cookie` header to persist the CSRF token value on the client.
typo: is installed, **the** initial response...

2024-07-07 06:55 UTC, danialkeimasi commented on README.md
> +If user does not have a CSRF token, ensure that one is generated and included in the initial request to the NextJS
It would be better to mention that this is enabled by default.

2024-07-08 18:42 UTC, Lizards commented
Thanks for the feedback, @danialkeimasi.  Please take a look again.

2024-07-10 16:04 UTC, danialkeimasi commented
Looks good.

2024-07-10 16:05 UTC, merged